name = "neonwave"
compatibility_date = "2024-04-03"
pages_build_output_dir = "public"

[vars]
# Variables d'environnement par défaut
JWT_SECRET = "neonwave-secret-2026"
SPOTIFY_MARKET = "FR"

[[d1_databases]]
binding = "DB"
database_name = "neonwave-db"
database_id = "3d4aaec5-7fa6-4e3b-93f2-16227a708dc1"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "neonwave-tracks"
